import os
import sys
import time

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from dataset.urbansound_dataset import get_fold_dataloaders
from models.cnn import UrbanSoundCNN
from attacks.fgsm import get_fgsm_attack
from attacks.bim  import get_bim_attack
from train.train import CONFIG, get_device, evaluate


# ── configs ───────────────────────────────────────────────────────────────────

ADV_FGSM_CONFIG = {
    **CONFIG,
    "attack_type": "fgsm",
    "adv_epsilon": 0.03,
    "adv_ratio":   0.5,
}

ADV_BIM_CONFIG = {
    **CONFIG,
    "attack_type": "bim",
    "adv_epsilon": 0.03,
    "adv_ratio":   0.5,
    "bim_steps":   7,     # fewer steps than evaluation to keep training time reasonable
}

# backward-compat alias
ADV_CONFIG = ADV_FGSM_CONFIG


# ── internal helper ───────────────────────────────────────────────────────────

def _build_attack(model, cfg):
    """Instantiate the attack object specified by cfg["attack_type"]."""
    attack_type = cfg.get("attack_type", "fgsm")
    if attack_type == "fgsm":
        return get_fgsm_attack(model, cfg["adv_epsilon"])
    elif attack_type == "bim":
        steps = cfg.get("bim_steps", 7)
        alpha = cfg["adv_epsilon"] / steps
        return get_bim_attack(model, cfg["adv_epsilon"], alpha, steps)
    else:
        raise ValueError(f"Unknown attack_type: {attack_type!r}. Use 'fgsm' or 'bim'.")


# ── training loop ─────────────────────────────────────────────────────────────

def adv_train_one_epoch(
    model:     nn.Module,
    loader:    DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device:    torch.device,
    cfg:       dict,
) -> tuple[float, float]:
    """One epoch of adversarial training using FGSM or BIM.

    For each batch a fraction (cfg["adv_ratio"]) of samples is replaced with
    adversarial examples generated by the chosen attack before the forward pass.
    The model trains on a mix of clean and adversarial inputs.

    Args:
        model:     Model (will be switched between eval/train as needed).
        loader:    Training DataLoader.
        criterion: nn.CrossEntropyLoss.
        optimizer: Adam optimizer.
        device:    CPU / CUDA / MPS.
        cfg:       Must contain attack_type, adv_epsilon, adv_ratio.
                   If attack_type == "bim" also needs bim_steps.

    Returns:
        (average_loss, accuracy_percent)
    """
    total_loss = 0.0
    correct    = 0
    total      = 0

    # build once per epoch — torchattacks holds a reference to the model object
    # so it always uses the current weights without needing to be rebuilt each batch
    attack = _build_attack(model, cfg)

    for specs, labels in loader:
        specs  = specs.to(device)
        labels = labels.to(device)

        batch_size = specs.size(0)
        n_adv      = max(1, int(batch_size * cfg["adv_ratio"]))

        # torchattacks requires eval mode for deterministic gradient computation
        # (disables Dropout, BatchNorm uses running stats)
        model.eval()
        adv_specs = attack(specs[:n_adv], labels[:n_adv]).detach()
        model.train()

        # first n_adv samples are adversarial, remainder are clean
        # label order matches: labels[:n_adv] for adv, labels[n_adv:] for clean
        mixed  = torch.cat([adv_specs, specs[n_adv:]], dim=0)
        logits = model(mixed)
        loss   = criterion(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * batch_size
        correct    += (logits.argmax(dim=1) == labels).sum().item()
        total      += batch_size

    return total_loss / total, 100.0 * correct / total


# ── fold runner ───────────────────────────────────────────────────────────────

def adv_train_fold(
    fold:        int,
    epochs:      int  = None,
    cfg:         dict = ADV_FGSM_CONFIG,
    model_class        = UrbanSoundCNN,
) -> dict:
    """Adversarially train a model from scratch for one fold of 10-fold CV.

    Args:
        fold:        Test fold (1–10).
        epochs:      Training epochs (defaults to cfg["epochs"]).
        cfg:         Config dict — must include attack_type, adv_epsilon, adv_ratio,
                     and bim_steps if attack_type == "bim".
        model_class: Model class to instantiate.

    Returns:
        {"best_val_acc", "history", "checkpoint_path"}
    """
    if epochs is None:
        epochs = cfg["epochs"]

    device      = get_device()
    attack_type = cfg.get("attack_type", "fgsm")

    print(f"\n{'='*60}")
    print(f" [ADV TRAIN / {attack_type.upper()}] Fold {fold}/10  |  device: {device}")
    print(f" ε={cfg['adv_epsilon']}  ratio={cfg['adv_ratio']}", end="")
    if attack_type == "bim":
        print(f"  steps={cfg.get('bim_steps', 7)}", end="")
    print()
    print(f"{'='*60}")

    train_loader, val_loader = get_fold_dataloaders(
        root_dir             = cfg["data_root"],
        test_fold            = fold,
        batch_size           = cfg["batch_size"],
        num_workers          = cfg["num_workers"],
        max_samples_per_fold = cfg.get("max_samples_per_fold"),
    )

    model     = model_class(num_classes=cfg["num_classes"], dropout=cfg["dropout"]).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg["lr"])

    os.makedirs(cfg["save_dir"], exist_ok=True)
    checkpoint_path = os.path.join(cfg["save_dir"], f"best_fold{fold}.pt")

    best_val_acc = 0.0
    history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}

    for epoch in range(1, epochs + 1):
        t0 = time.time()

        train_loss, train_acc = adv_train_one_epoch(
            model, train_loader, criterion, optimizer, device, cfg
        )
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        elapsed = time.time() - t0
        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        improved = val_acc > best_val_acc
        if improved:
            best_val_acc = val_acc
            torch.save(
                {
                    "epoch":            epoch,
                    "fold":             fold,
                    "model_state_dict": model.state_dict(),
                    "val_acc":          val_acc,
                    "val_loss":         val_loss,
                    "config":           cfg,
                },
                checkpoint_path,
            )

        marker = "  ✓ saved" if improved else ""
        print(
            f" Epoch {epoch:>3}/{epochs} | "
            f"train loss {train_loss:.4f}  acc {train_acc:5.1f}% | "
            f"val loss {val_loss:.4f}  acc {val_acc:5.1f}%  "
            f"[{elapsed:.1f}s]{marker}"
        )

    print(f"\n Best val acc for fold {fold}: {best_val_acc:.2f}%")
    return {"best_val_acc": best_val_acc, "history": history, "checkpoint_path": checkpoint_path}
